---
functional:
  - Пользователь должен иметь возможность создать игру
  - Пользователь должен иметь возможность выбрать свой уровень
  - Пользователь должен иметь возможность выбрать тип игры (с ботом, с другом, с другими пользователями)
  - Пользователь должен иметь возможность выбрать время игры
  - Пользователь должен иметь возможность выбрать задание
  - Пользователь должен иметь возможность писать код
  - Пользователь должен иметь возможность видеть код соперника
  - Пользователь должен иметь возможность проверить свой код
  - Пользователь должен иметь возможность зарегистрироваться на сайте
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность видеть таблицу лидеров
